# Generated by Django 4.1 on 2022-08-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_remove_mailing_time_end_remove_mailing_time_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='time_create',
            new_name='sending_time',
        ),
    ]
