# Generated by Django 4.1 on 2022-08-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_rename_time_create_message_sending_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sending_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sending time'),
        ),
    ]
